### ISSUE TITLE
Analogue Button Not Working

### ISSUE THREAD

**Issue by dji85** [agg23/openfpga-wonderswan#1]
### Version (or build number)

1.0.0

### Actual Behavior

Pressing the Analogue/home button does not bring up the system menu

**Comment by agg23** [comment]
This is an issue with Analogue OS 1.1 beta 7. If I understood what people were discussing, there is a new UI screen that notifies the user about some new feature, that appears when navigating from the root screen to the openFPGA screen. If you do not go through that screen, the Analogue button doesn't work correctly.

So I think the solution is:
1. Turn on Pocket
2. Navigate to the root screen (Cartridge, Library, Memories, openFPGA, etc.)
3. Navigate to openFPGA
4. You should see the new feature screen. Dismiss it
5. The Analogue button should now function in cores

I have not experienced this personally, so I may have gotten something wrong with these instructions. In any case, it is unrelated to my core.

**Comment by dji85** [comment]
Worked perfectly, thanks @agg23 ! Strange, I have two Pockets that I've upgraded; one displayed the new feature screen after the last upgrade but this one did not. Appreciate the assist (and apologies for the bogus bug).
