### ISSUE TITLE
Star Hearts SRAM wiped upon new boot (copy protection)

### ISSUE THREAD

**Issue by Goldanas** [agg23/openfpga-wonderswan#2]
### Version (or build number)

1.0.0

### Steps to reproduce

- Launch game
- Select default and only option on title screen
- Button through naming character until you get to gameplay
- Try to exit tent by talking to chief, then button through his text.
- Walk to the left two screens, and then enter the hut in the bottom left
- Talk to the Priestess and receive a weapon and drum
- Exit the tent
- Press Y1 to bring up the save prompt, an then select the default options to save.
- Reboot the core, or load up another game, and then load up Star Hearts again

### Expected Behavior

Game launches and you can load your save

### Actual Behavior

The game gives a corruption prompt on launch and notifies you that it's going to wipe your save

### Additional Context

Star Hearts specifies itself to only use a small amount of SRAM, but it actually writes just a bit more data outside of that bounds, likely as a protection measure against flash carts back in the day. If it can't write that data, or if it doesn't exist, then on next boot, the game will assume the data is corrupted. You can actually patch the header to expand the SRAM space the core (and most emulators) assumes this game to have and it should allow for saving, but ideally a patch shouldn't be necessary, and the core should ideally solve for this issue (or just ignore the SRAM limits in this case or something).

**Comment by agg23** [comment]
Ooh interesting. Thank you for the detailed instructions. I was able to repro.

I've reached out to Robert to discuss.

**Comment by RobertPeip** [comment]
How is the core/emulator supposed to know there is more sram available when the header doesn't tell it?

The only possibility would be to detect this is "Star Hearts" and do it automatically, which is in my opinion a worse solution.

We have such behavior in GBA the other way around, where the game uses SRAM it doesn't have at all(uses EEPROM) and the core/emulator cannot know, so lists of game titles are required. This is not a better solution than fixing/patching the header.

edit: 
if you think we could just ignore the header and write more data if the game tries to, then that will not work. Games often have bugs and depend on the write address to wrap inside the available memory.

**Comment by Goldanas** [comment]
I don't disagree that programmatically it's not good to make exceptions or whitelists, however from a user perspective, you can't play the game as intended, or as the original hardware / cart would.

It's your decision for how you would want to treat this. When it comes to anti-piracy / copy protection (if indeed that's what this is), I've seen other emulators / ODEs / cores go either way. Some implement schemes to be able to play the games as the original hardware would, or obey the copy protection as the original hardware would.

It's at your discretion, but if someone wants the patch, it's available with a common rom hack, and I've also attached it here.
[Star Hearts - Hoshi to Daichi no Shisha (Japan) (Emulator Patch).wsc.zip](https://github.com/agg23/openfpga-wonderswan/files/10442322/Star.Hearts.-.Hoshi.to.Daichi.no.Shisha.Japan.Emulator.Patch.wsc.zip)

**Comment by RobertPeip** [comment]
Yes, the header infos seem to be wrong for some games.
A dcoumentation can be found here:
http://daifukkat.su/docs/wsman/#cart_meta

I understand it's inconvenient for the user to fix it, but i still think it's the correct way because there are headers that contain that information. If we cannot trust the header, we also might not trust the game ID and therefore could not apply patches...


edit: of course @agg23 is free to decide to apply auto patches for it, maybe even in the softcore that loads the rom? But for the original mister core i will not do it

**Comment by Goldanas** [comment]
I'd be interested to know what elements of the header the original system obeys, and what it ignores. I imagine manufacturer and cart ID are ignored, but obviously orientation and start positions are obeyed.

I'm curious how often the save type is obeyed by the system, or if it always relies on the program code to do the appropriate thing, considering the save type is always stored on the cart itself rather than the system. Of course, this is semantics vs modern system design, and might not be applicable to the current situation.

**Comment by RobertPeip** [comment]
The "system" is the "game", there is no underlying OS or anything for WS. The game does not access the bootrom again after starting.

For the Header: the bootrom does indeed read the header and the game also at the very beginning. However, the RAM info byte is not read by both.

**Comment by agg23** [comment]
Closing. I agree with Robert and I don't think there is anything actionable here.
