### ISSUE TITLE
EEPROM not supported?

### ISSUE THREAD

**Issue by Weef-Bellington** [agg23/openfpga-wonderswan#3]
### Ask a question

Does this core support games that save in EEPROM format?

I dumped the rom and save file from my Engacho! cart. The cart reader generated the save file in .eep format. When I copy that file to the Pocket in the appropriate folder and load the rom in the Wonderswan core, it does not seem to recognize the save. Changing the extension to .sav does not seem to make a difference.

I have similar issues with other EEPROM games.

All the SRAM save files I dumped work just fine with their corresponding roms in the Wonderswan core.

**Comment by RobertPeip** [comment]
Did you try to save ingame in any of these games and see what file is generated, then replace it?

Maybe the file you read from the cart also has some additional header or byte order swapped.

**Comment by Weef-Bellington** [comment]
In-game saving does not work at all for Engacho! and another EEPROM game I tried, Another Heaven. I haven't looked in depth at any other EEPROM games.

Engacho! autosaves after you complete every puzzle. So when you complete puzzle 2 and the game loads you into puzzle 3, if you close the game and start again later, you can begin at puzzle 3. 

1. I loaded Engacho! in the Wonderswan core, solved the first puzzle, and quit to the main menu.
2. I entered puzzle mode again to confirm I could pick up again at puzzle 2.
3. I closed the core out to the main Analogue OS menu.
4. When I loaded Engacho! again, my progress was gone and I had the option only to start at puzzle 1.

Another Heaven has a manual save function. I started a new game, paged through some of the text (it's a visual novel), then saved my game. I closed out to the main menu to confirm the "Continue" option appeared. Then I quit the core. When I loaded Another Heaven again, the "Continue" option was gone, leaving only the option to start a new game.

The core does generate a .sav file for both games. I opened them up in a hex editor. Both of them are just repeating sequences of two numbers: 34 and 12 for Another Heaven and 4E and 41 for Engacho!. They're both also much larger than the .eep file I dumped from each cartridge.

**Comment by agg23** [comment]
Sorry for making you go through that effort. Apparently just while you were writing this comment, I was doing some testing as well.

Yes, something is not working with EEPROM preservation. Not sure when I'll get around to it, but I'll look into it soon.

Sorry about that

**Comment by Weef-Bellington** [comment]
Thanks @agg23 ! No hurry. And thanks @RobertPeip for your help as well, and for developing this core in the first place!

**Comment by agg23** [comment]
Sorry for the delay. The issue should be fixed, and you can try out the beta here. If I hear it's OK from my testing group and you, I will release it.

[agg23.WonderSwan_1.0.1-beta1_2023-05-04.zip](https://github.com/agg23/openfpga-wonderswan/files/11400225/agg23.WonderSwan_1.0.1-beta1_2023-05-04.zip)

**Comment by Weef-Bellington** [comment]
Thanks! I'll test it tonight and let you know.

**Comment by Weef-Bellington** [comment]
It works! Save data persists after I close the core and reload it, in both of the EEPROM games I tested. The core also recognizes the saves I dumped from the cartridges for both games.

Thanks @agg23 for your attention to this!

**Comment by agg23** [comment]
Fixed in 1.0.1. Thanks for the report.
